
services:
    redis:
        image: "redis:alpine"
        ports:
            - "6379:6379"
        networks:
            - robotito
    backend: 
        build:
            context: .
            dockerfile: node.dockerfile
        ports:
            - "3000:3000"
        environment: 
            - NODE_ENV=production
        networks:
            - robotito
        depends_on:
            - redis
networks:
    robotito:
